version: "3"

vars:
  repo: github.com/shirooe/money-flow

tasks:
  protoc:
    desc: Generate Go code from .proto files
    cmds:
      - protoc libs/api/**/*.proto --proto_path=.
        --go_out=. --go_opt=module={{.repo}}
        --go-grpc_out=. --go-grpc_opt=module={{.repo}}
  lint:
    desc: Lint Go code
    cmd: golangci-lint run ./... -c .golangci.yml

  migration-create:
    desc: Create migration files from args
    cmd: migrate create -ext sql -dir apps/{{.dir}}/migrations -tz UTC {{.name}}
    requires:
      vars: ["dir", "name"]

  migration-up:
    desc: Run migrations
    cmd: migrate -path apps/{{.dir}}/migrations -database {{.db}} up
    requires:
      vars: ["dir", "db"]

  migration-down:
    desc: Run migrations
    cmd: migrate -path apps/{{.dir}}/migrations -database {{.db}} down
    requires:
      vars: ["dir", "db"]
